import { Weapon } from './Weapon.js';

export const WEAPON_DEFINITIONS: Record<string, Weapon> = {
  pistol: new Weapon({
    id: 'pistol',
    name: 'Pistol',
    displayName: '制式手枪',
    damage: 28,
    fireRate: 5,
    magazineSize: 12,
    reloadTime: 1.5,
    spread: 0.04,
    projectileSpeed: 50,
    switchTime: 0.24,
    range: 48
  }),
  heavy_pistol: new Weapon({
    id: 'heavy_pistol',
    name: 'Heavy Pistol',
    displayName: '重型手枪',
    damage: 55,
    fireRate: 2.2,
    magazineSize: 7,
    reloadTime: 1.9,
    spread: 0.05,
    projectileSpeed: 58,
    switchTime: 0.3,
    range: 65
  }),
  rifle: new Weapon({
    id: 'rifle',
    name: 'Assault Rifle',
    displayName: '突击步枪',
    damage: 36,
    fireRate: 9.5,
    magazineSize: 30,
    reloadTime: 2.35,
    spread: 0.055,
    projectileSpeed: 80,
    switchTime: 0.42,
    range: 90
  }),
  defender_rifle: new Weapon({
    id: 'defender_rifle',
    name: 'Defender Rifle',
    displayName: '防守步枪',
    damage: 33,
    fireRate: 10,
    magazineSize: 30,
    reloadTime: 2.25,
    spread: 0.045,
    projectileSpeed: 80,
    switchTime: 0.4,
    range: 86
  }),
  sniper: new Weapon({
    id: 'sniper',
    name: 'Sniper Rifle',
    displayName: '狙击枪',
    damage: 115,
    fireRate: 0.8,
    magazineSize: 5,
    reloadTime: 3.3,
    spread: 0.015,
    projectileSpeed: 120,
    switchTime: 0.64,
    range: 130
  }),
  smg: new Weapon({
    id: 'smg',
    name: 'SMG',
    displayName: '冲锋枪',
    damage: 22,
    fireRate: 13,
    magazineSize: 30,
    reloadTime: 2,
    spread: 0.075,
    projectileSpeed: 62,
    switchTime: 0.28,
    range: 45
  }),
  shotgun: new Weapon({
    id: 'shotgun',
    name: 'Shotgun',
    displayName: '散弹枪',
    damage: 18,
    fireRate: 1.1,
    magazineSize: 8,
    reloadTime: 2.8,
    spread: 0.22,
    projectileSpeed: 40,
    switchTime: 0.45,
    range: 26
  }),
  knife: new Weapon({
    id: 'knife',
    name: 'Knife',
    displayName: '战术刀',
    damage: 55,
    fireRate: 1.8,
    magazineSize: 1,
    reloadTime: 0,
    spread: 0,
    projectileSpeed: 0,
    ammoConsumed: false,
    isMelee: true,
    switchTime: 0.18,
    range: 2.4
  })
};
