#!/bin/bash
#
# find-cs16-icons.sh - Helper script to search for CS 1.6 weapon icons
#

echo "Searching for CS 1.6 weapon icons..."
echo "===================================="
echo ""
echo "Web search terms to use:"
echo "-------------------------"
echo "- 'CS 1.6 weapon sprites HUD'"
echo "- 'CS 1.6 weapon icons blue green'"
echo "- 'CS 1.6 buy menu images'"
echo "- 'Counter-Strike 1.6 HUD sprites'"
echo "- 'CS 1.6 weapon sprites pack GameBanana'"
echo ""
echo "Good sources to check:"
echo "-----------------------"
echo "- GameBanana (https://gamebanana.com)"
echo "- Sprite databases (https://spritedatabase.net)"
echo "- CS 1.6 community forums"
echo "- GitHub sprite repositories"
echo ""
echo "Icon requirements:"
echo "------------------"
echo "- HUD icons: 24x24 pixel style, blue/green pixel art"
echo "- Buy menu: Larger preview images"
echo "- Format: PNG, GIF, or BMP (will be converted later)"
echo "- Style: Authentic CS 1.6 look"
echo ""
echo "Weapons needed:"
echo "---------------"
echo "Pistols: glock, usp, p228, deagle, fiveseven"
echo "SMGs: mp5, tmp, p90, mac10, ump45"
echo "Shotguns: m3, xm1014"
echo "Rifles: ak47, m4a1, sg552, aug, galil, famas"
echo "Snipers: scout, awp, sg550, g3sg1"
echo "Machine gun: m249"
echo "Melee: knife"
echo "Equipment: hegrenade"
echo ""
echo "Next steps after downloading:"
echo "-----------------------------"
echo "1. Place HUD icons in scripts/cs16-raw/hud/"
echo "2. Place buy menu icons in scripts/cs16-raw/buy/"
echo "3. Remove the .placeholder files"
echo "4. Run Task 3 to process into final format"
